dbtlearn:
  outputs:
    dev:
      account: ag77335.ap-southeast-1
      database: AIRBNB
      password: dbtPassword123
      role: transform
      schema: DEV
      threads: 5
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
  
